<?php

declare(strict_types=1);

namespace App\Domain\Settlement\Enums;

enum SettlementEventType: string
{
    case SETTLEMENT_CREATED = 'SETTLEMENT_CREATED';
    case DUPLICATE_REQUEST_RECEIVED = 'DUPLICATE_REQUEST_RECEIVED';
    case SETTLEMENT_REQUEST_REJECTED = 'SETTLEMENT_REQUEST_REJECTED';
    case PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED';
    case PROVIDER_TIMEOUT = 'PROVIDER_TIMEOUT';
    case SETTLEMENT_FAILED = 'SETTLEMENT_FAILED';
    case SETTLEMENT_CONFIRMED = 'SETTLEMENT_CONFIRMED';
    case RECONCILIATION_QUEUED = 'RECONCILIATION_QUEUED';
    case INVOICE_RECONCILED = 'INVOICE_RECONCILED';
}
